# Generated by Django 3.1 on 2020-08-26 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paymeuz', '0002_auto_20200826_1127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='state',
        ),
    ]
